version: '3'
services:
  web:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"

    # environment:
    #   - PORT=3000
    #   - MONGODB_URI=mongodb://mongo:27017/your-database-name